/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMarketNFT, IMarketNFTInterface } from "../IMarketNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_order",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256",
      },
    ],
    name: "buyToken",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_order",
        type: "uint256",
      },
    ],
    name: "cancelSellToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_tokenIds",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "readyToSellToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_order",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "setCurrentPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMarketNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IMarketNFTInterface {
    return new utils.Interface(_abi) as IMarketNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMarketNFT {
    return new Contract(address, _abi, signerOrProvider) as IMarketNFT;
  }
}
