/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface NFTFactoryInterface extends ethers.utils.Interface {
  functions: {
    "NFT_Origin()": FunctionFragment;
    "clone(string,string,address,uint256,uint256,string)": FunctionFragment;
    "cloneLength()": FunctionFragment;
    "clones_(uint256)": FunctionFragment;
    "getAddressForAddress(address)": FunctionFragment;
    "getAllTokenAddress()": FunctionFragment;
    "getAllTokenAddressForUser(address)": FunctionFragment;
    "getOwnerToken(address,uint256)": FunctionFragment;
    "getTokenMintForAddress(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "NFT_Origin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clone",
    values: [string, string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "cloneLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "clones_",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressForAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTokenAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTokenAddressForUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenMintForAddress",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "NFT_Origin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clone", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cloneLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clones_", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTokenAddressForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenMintForAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class NFTFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: NFTFactoryInterface;

  functions: {
    NFT_Origin(overrides?: CallOverrides): Promise<[string]>;

    clone(
      name_: string,
      symbol_: string,
      owner_: string,
      amount: BigNumberish,
      fee_: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cloneLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    clones_(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    getAddressForAddress(
      users_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getAllTokenAddress(overrides?: CallOverrides): Promise<[string[]]>;

    getAllTokenAddressForUser(
      user_: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getOwnerToken(
      users_: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTokenMintForAddress(
      user_: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  NFT_Origin(overrides?: CallOverrides): Promise<string>;

  clone(
    name_: string,
    symbol_: string,
    owner_: string,
    amount: BigNumberish,
    fee_: BigNumberish,
    uri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cloneLength(overrides?: CallOverrides): Promise<BigNumber>;

  clones_(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getAddressForAddress(
    users_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getAllTokenAddress(overrides?: CallOverrides): Promise<string[]>;

  getAllTokenAddressForUser(
    user_: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getOwnerToken(
    users_: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTokenMintForAddress(
    user_: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    NFT_Origin(overrides?: CallOverrides): Promise<string>;

    clone(
      name_: string,
      symbol_: string,
      owner_: string,
      amount: BigNumberish,
      fee_: BigNumberish,
      uri: string,
      overrides?: CallOverrides
    ): Promise<string>;

    cloneLength(overrides?: CallOverrides): Promise<BigNumber>;

    clones_(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getAddressForAddress(
      users_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getAllTokenAddress(overrides?: CallOverrides): Promise<string[]>;

    getAllTokenAddressForUser(
      user_: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getOwnerToken(
      users_: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenMintForAddress(
      user_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    NFT_Origin(overrides?: CallOverrides): Promise<BigNumber>;

    clone(
      name_: string,
      symbol_: string,
      owner_: string,
      amount: BigNumberish,
      fee_: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cloneLength(overrides?: CallOverrides): Promise<BigNumber>;

    clones_(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getAddressForAddress(
      users_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAllTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getAllTokenAddressForUser(
      user_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOwnerToken(
      users_: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenMintForAddress(
      user_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    NFT_Origin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    clone(
      name_: string,
      symbol_: string,
      owner_: string,
      amount: BigNumberish,
      fee_: BigNumberish,
      uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cloneLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    clones_(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddressForAddress(
      users_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllTokenAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAllTokenAddressForUser(
      user_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOwnerToken(
      users_: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenMintForAddress(
      user_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
