
import { ethers } from "hardhat";

async function main() {

const MArket = await ethers.getContractFactory("Market");
const market = await MArket.deploy();//declarar la address necesaria

await market.deployed(); 

console.log("market deployed to:", market.address);
}
main().catch((error) => {
console.error(error);
process.exitCode = 1;
});
//Successfully generated ByteCode and ABI for Contract Address [0x5a4D30403b9b52B45935d4903Bc51ABEB24304c0]