
import { ethers } from "hardhat";

async function main() {
    
const ERC721UUPS = await ethers.getContractFactory("ERC721UUPS");
const ERC721 = await ERC721UUPS.deploy();

await ERC721.deployed(); 

console.log("ERC721UUPS deployed to:", ERC721.address);
}

main().catch((error) => {
console.error(error);
process.exitCode = 1;
});
//Successfully generated ByteCode and ABI for Contract Address [0x74AF6474a544378BaF7B580001647b4E5c6FaEF0]