import { ethers } from "hardhat";

async function main() {

const clone = await ethers.getContractFactory("NFTFactory");
const clonar = await clone.deploy();

await clonar.deployed(); 

console.log("clonar deployed to:", clonar.address);
}

main().catch((error) => {
console.error(error);
process.exitCode = 1;
});
//Successfully generated ByteCode and ABI for Contract Address [0xfabB3F419a286285a5E47C8Af9Fa7CD7D31708BB]